const MATCH_CONSTRAINTS = {
  GTC: 'GTC',
  IOC: 'IOC',
  FOK: 'FOK',
  FOK_BUDGET: 'FOK_BUDGET',
  IOC_BUDGET: 'IOC_BUDGET'
};

const ORDER_TYPES = {
  LIMIT_ORDER: 'LIMIT_ORDER',
  MARKET_ORDER: 'MARKET_ORDER'
};

const DIRECTIONS = {
  BID: 'BID',
  ASK: 'ASK'
};

const REJECTION_REASONS = {
  OPERATION_NOT_MATCHED_MATCHC: 'OPERATION_NOT_MATCHED_MATCHC',
  ORDER_TYPE_NOT_MATCHED_MATCHC: 'ORDER_TYPE_NOT_MATCHED_MATCHC',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND'
};

module.exports = {
  MATCH_CONSTRAINTS,
  ORDER_TYPES,
  DIRECTIONS,
  REJECTION_REASONS
};
